on: [push]

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}    

jobs:
  pytest:
    uses: davidslusser/actions/.github/workflows/coveralls.yaml@coveralls
    with:
      src: "src"
      options: ""
      pip_install_command: "pip install -e .[dev]"
