on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: "pytest"
    steps:
      - uses: davidslusser/actions_python_pytest@test
        with:
          src: "src"
          options: "-v"
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.11"
