on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - name: actions_python_ruff
        uses: davidslusser/actions_python_ruff@main
        with:
            src: "src"
            options: "-v"